### ISSUE TITLE
There is no chance to put any html attributes to an element

### ISSUE THREAD

**Issue by Neftedollar** [kunjee17/GreenPrint#15]
For example:
```fsharp
Button.button [ Active true; Props [ HTMLAttr.Custom ("lang","ru") ] ] [ str "Привет!" ]
```
I can't do it.
So I can add `Props of IHTMLProp list `
```fsharp
    | Text of ReactElement
    | Type of ButtonType
    | Props of IHTMLProp list <- this one
    interface IHTMLProp
and something like
```fsharp
    let inline button (props : IHTMLProp list) (elems : ReactElement list) : ReactElement =
      ///this one
       let props  = props |> List.fold ( fun s x -> match x with 
                                                                     | Props x -> s @ x 
                                                                     | a -> (a :> IHTMLProp ) :: s  ) []
        ofImport "Button" "@blueprintjs/core"
            (keyValueList CaseRules.LowerFirst props) elems
```
and then use the example above.
Is this solution ok?
Should I create PR?

**Comment by kunjee17** [comment]
Thanks for a issue. I might have missed to put elem in function. Give me a day and I will get back to you.

**Comment by kunjee17** [comment]
@Neftedollar I am extremely sorry.  I was writing code from docs and I totally forgot to add HTML props. It is not there in any component. I will add to all components. And if you like to do the honors be my guest. :) 

You might need a common function to join html props
```
let props  = props |> List.fold ( fun s x -> match x with 
                                                                     | Props x -> s @ x 
                                                                     | a -> (a :> IHTMLProp ) :: s  ) []
```
This can be abstracted away to use in all components. Just let me know if you want to give PR. Else I ll do it. Again thanks for pointing out.

**Comment by kunjee17** [comment]
On second thought it is too many changes. Give me half day. I ll update repo and nuget packages. @Neftedollar

**Comment by Neftedollar** [comment]
I can do it. 
I tryed to do something like this project (f.e. Fable.SemanticUI) but sometimes I have no time to move project forward. But I belive Fable need something like GreenPrint or SemanticUI. 
So if I can do something now, it would be awesome.

**Comment by kunjee17** [comment]
@Neftedollar thanks man. All yours. I am waiting for PR then. Once changes are in master will update the nugets. 

Again thanks a lot.

**Comment by kunjee17** [comment]
If you like to contribute more, by all means you are welcome @Neftedollar . :)

**Comment by Neftedollar** [comment]
@kunjee17  I would like it

**Comment by Neftedollar** [comment]
@kunjee17 
My fail! 
with `let inline button (props : ` **IHTMLProp list**`)` 
I can add any IHtmlPops, but I can send any other props and it's not typesafe. 
I can change version above to `let inline button (props : ` **IButtonProps list**`)`  and then add parser of option for type safety.
Should I?

**Comment by kunjee17** [comment]
I was trying the same thing and failed because of types. I remember changing it to IHTMLProp because I couldn't add HTMLProp there while using it. I guess you can do it now. Change it to IButtonProp and I guess there is no need to inheritance also. But keep it in case it required.

**Comment by kunjee17** [comment]
Closing this issue as @Neftedollar solved it.
